# Generated by Django 5.1.4 on 2025-04-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
            ],
        ),
    ]
